// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcskmvvwpzmfdbwwcuis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjc2ttdnZ3cHptZmRid3djdWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjYyNDksImV4cCI6MjA3MTk0MjI0OX0.y1Vwk5G0o6ekQgjrsm8q_UPg8ALejblTCDed_beey4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});